name: testtcp
version: git
summary: OfflineIMAP
description: |
test.
confinement: devmode
base: core18

parts:
  test-offlineimap-nirmalkumar06:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - python-six

apps:
  test-offlineimap-nirmalkumar06:
    command: bin/offlineimap
