name: testtcp
version: git
summary: OfflineIMAP
description: |
  OfflineIMAP is software that downloads your email mailbox(es) as local
  Maildirs. OfflineIMAP will synchronize both sides via IMAP.
confinement: devmode
base: core18

parts:
  test-offlineimap-nirmalkumar06:
    plugin: python
    python-version: python2
    source: .
    stage-packages:
      - python-six

apps:
  test-offlineimap-nirmalkumar06:
    command: bin/offlineimap
