name: tcp-server
version: git
summary: OfflineIMAP
description: |
  OfflineIMAP is software that downloads your email mailbox(es) as local
  Maildirs. OfflineIMAP will synchronize both sides via IMAP.
confinement: devmode
base: core18

parts:
  tcp-server:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - python-six

apps:
  tcp-server:
    command: bin/offlineimap
